//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarTrack.Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Antinna
    {
        public int Id { get; set; }
        public int ReaderId { get; set; }
        public int LocationId { get; set; }
        public string Name { get; set; }
        public string Detail { get; set; }
        public int Type { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Reader Reader { get; set; }
    }
}
