//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarTrack.Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asset()
        {
            this.Movements = new HashSet<Movement>();
            this.SubAssets = new HashSet<SubAsset>();
        }
    
        public int Id { get; set; }
        public string AssetId { get; set; }
        public int SiteId { get; set; }
        public int LocationId { get; set; }
        public int CategoryId { get; set; }
        public int TypeId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public bool SubAsset { get; set; }
        public Nullable<bool> MultibleSubSelected { get; set; }
        public string Name { get; set; }
        public string TagId { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string Details { get; set; }
        public string SerialNumber { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<int> CurrentLocation { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Department Department { get; set; }
        public virtual Location Location { get; set; }
        public virtual Location Location1 { get; set; }
        public virtual Site Site { get; set; }
        public virtual Type Type { get; set; }
        public virtual AssetImage AssetImage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movement> Movements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubAsset> SubAssets { get; set; }
    }
}
